-- BiciTodo Supabase Alerts Table Schema
-- Ejecuta este script en el "SQL Editor" de Supabase para crear la estructura de datos.

CREATE TABLE IF NOT EXISTS alertas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_usuario TEXT NOT NULL,
    id_producto INTEGER NOT NULL,
    precio_actual INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Índices de optimización para búsquedas eficientes
CREATE INDEX IF NOT EXISTS idx_alertas_producto ON alertas(id_producto);
CREATE INDEX IF NOT EXISTS idx_alertas_email ON alertas(email_usuario);
