-- BiciTodo Supabase Alerts Table Schema
-- Ejecuta este script en el SQL Editor de Supabase.
-- La app inserta/actualiza alertas desde el backend, usando variables de entorno.

CREATE TABLE IF NOT EXISTS public.alertas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_usuario TEXT NOT NULL,
    id_producto INTEGER NOT NULL,
    precio_objetivo INTEGER NOT NULL,
    precio_actual INTEGER,
    producto_nombre TEXT,
    marca TEXT,
    categoria TEXT,
    tienda_mejor_precio TEXT,
    url_producto TEXT,
    image_url TEXT,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    notificado BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT alertas_email_producto_unique UNIQUE (email_usuario, id_producto)
);

CREATE INDEX IF NOT EXISTS idx_alertas_producto ON public.alertas(id_producto);
CREATE INDEX IF NOT EXISTS idx_alertas_email ON public.alertas(email_usuario);
CREATE INDEX IF NOT EXISTS idx_alertas_activa ON public.alertas(activa);

ALTER TABLE public.alertas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Backend service role manages alertas" ON public.alertas;
CREATE POLICY "Backend service role manages alertas"
ON public.alertas
FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');
